LBHackney-IT/mat-service

.circleci/config.yml, serverless.yml
- rename serverless service to match naming convention used on MaT account
- remove commented out lines
- update serverless to use new serverless.js command
- add build to deployment step
- remove --config flag from the serverless command. It's not required with default file names
=> Rename serverless service

.circleci/config.yml, database.json, db/migrations/20200714104006-add-test-table.js, db/migrations/sqls/20200714104006-add-test-table-down.sql, db/migrations/sqls/20200714104006-add-test-table-up.sql, package-lock.json, package.json, serverless.yml
- Add initial database resource using serverless
- Add db-migrate package and sample migrations
- Required for setting up initial database and managing database migrations through source control
- This covers only local migrations for now
- Investigate automated migrations using CircleCi
- Further configuration (security, backups etc.) required for the database
=> SV-64 #UAT #comment Add db resource and migrations

.github/pull_request_template.md
Added a checklist to the PR template with test items initially
As discussed in planning meeting 15/07
=> Added checklist with test reminders to PR Template

.circleci/config.yml, serverless.yml
Add CloudFront distribution setup for serverless
This will enable us to setup friendly URLs and SSL certificates for our staging and production sites
CNAMEs used in this configuration are temporary for now just so we can use friendly URLs during development. They'll need to be updated once we switch over to final URLs
=> SV-76 #comment CloudFront distribution setup for serverless

.circleci/config.yml, serverless.yml
Add integration tests to the pipeline and fix an issue with unit tests. Also update some variable names to follow the naming convention used in the parameter store.
This automates the unit and integration tests in the pipeline. Integration tests are run against both staging and production environment.
API endpoints in the CircleCi environment are currently pointing to API gateway. These need to be updated once Hackney DNS has been updated
=> Sv 109 add integration tests to ci

authorizer.js, src/integration/auth.test.js, src/pages/_app.tsx, src/pages/login-redirect.tsx, src/tests/helpers/generateToken.ts, src/tests/pages/app.test.tsx, src/tests/pages/login-redirect.test.tsx, src/usecases/isLoggedIn.ts
Modified existing auth  tests to read groups from the env rather than hard coding.
Fix tests in non-dev envs
=> Fix: updated auth tests to use groups from env

serverless.yml
Add missing UI_PATH env var to serverless
This will set the correct redirect URL for the login link
=> add ui_path env var

.circleci/config.yml, cypress/integration/redirectPage/redirectPage.spec.ts, cypress/integration/workTrayPage/workTrayPage.spec.ts, package.json
Jira ticket:  [SV-105](https://hackney.atlassian.net/browse/SV-105)
-Tests the correct URL is loaded
-Tests the table tabs have the correct names on them
-Tests the table tabs display the correct data once they are clicked
-Tests sorting on the Name column
-Tests sorting on the Due/Completion column
Tests are currently failing on CircleCI
To ensure elements are displaying the correct names and once interacted with, have the correct behaviour with the correct data.
As is, the CircleCI tests fail when checking for the 'In Progress' tab name value:
"AssertionError: Timed out retrying: Expected to find content: 'In Progress' but never did.
cypress/integration/workTrayPage/workTrayPage.spec.ts"
This is may be due to hitting the redirect page for authentication
=> SV-105/Add Cypress tests on WorkTray

cypress/tsconfig.json
tsconfig scoping changes without the extra commits from SV-102
-->
The other commits are no longer necessary
=> Add type scoping tsconfig.json to Cypress folder and globally

.circleci/config.yml, serverless.yml
Add environment variables to serverless configuration
Configuration values are required by the CRM gateway
Production values have to be added to the AWS parameter store once we have confirmation on what they should be
=> Add CRM gateway env vars to serverless configuration

cypress/integration/trasPage/trasPage.spec.ts, db/migrations/20200817152810-create-tra-table.js, db/migrations/20200817153017-create-trapatchassociation-table.js, db/migrations/20200818073522-create-housingarea-table.js, db/migrations/20200819094838-add-user-table.js, db/migrations/sqls/20200714104006-add-test-table-down.sql, db/migrations/sqls/20200714104006-add-test-table-up.sql, db/migrations/sqls/20200817152810-create-tra-table-down.sql, db/migrations/sqls/20200817152810-create-tra-table-up.sql, db/migrations/sqls/20200817153017-create-trapatchassociation-table-down.sql, db/migrations/sqls/20200817153017-create-trapatchassociation-table-up.sql, db/migrations/sqls/20200818073522-create-housingarea-table-down.sql, db/migrations/sqls/20200818073522-create-housingarea-table-up.sql, db/migrations/sqls/20200819094838-add-user-table-down.sql, db/migrations/sqls/20200819094838-add-user-table-up.sql, package-lock.json, package.json, src/gateways/matDatabaseGateway.ts, src/gateways/matPostgresGateway.ts, src/interfaces/tra.ts, src/pages/api/tras.ts, src/pages/tras.tsx, src/tests/helpers/generateTRA.ts, src/tests/pages/api/tras.test.ts, src/tests/pages/login-redirect.test.tsx, src/usecases/api/getTRAsByPatchId.testPlaceholder.ts, src/usecases/api/getTRAsByPatchId.ts, src/usecases/ui/getTRAs.ts
Adds a rough and ready gateway to enable SV-65 and SV-107 to proceed.
Both these tickets require access to a postgres db. As such, we're looking to get this in early and improve on it as part of these two tickets.
Very rough format. Will be refactored and improved as part of ongoing work.
=> Add base gateway for tickets SV-65 and SV-107

.env.sample
Stu asked me to add the feed back link to the env sample file after all, I wasn't sure if I was allowed to push directly to master without someone giving it a once over.
=> Add Google doc feedback link to env sample file

.env.sample
Re-add CRM_CLOUD_URL and CRM_API_URL env vars in env sample file
=> Re-add CRM_CLOUD_URL and CRM_API_URL env vars in env sample file

src/gateways/crmGateway.ts, src/gateways/matPostgresGateway.ts, src/pages/api/userMappings.ts, src/pages/api/users.ts, src/usecases/api/checkUserMappingExists.test.ts, src/usecases/api/checkUserMappingExists.ts, src/usecases/api/createUser.ts, src/usecases/api/createUserMapping.test.ts, src/usecases/api/createUserMapping.ts, src/usecases/api/getUser.ts
SV-107
Adds routes for:
- checking if a user mapping exists in the postgres db
- creating a new user mapping
These will be needed as part of creating the link for our app between crm users and google authenticated users.
Need to finish up the routes for hitting crm user entity (create and get)
Need to plumb this into the UI side so this all runs at the same time as the login check.
=> Sv 107 Postgres DB Get and Create Routes

.circleci/config.yml
Modify CircleCI config to enable Cypress test on all commits. There are two different configs, one for branches using the dev server and one for master using the deployed service.
To increase deployment pipeline robustness.
=> Enable Cypress Testing In Branch Commits

.circleci/config.yml, cypress/integration/taskPage/taskPage.spec.ts, cypress/integration/workTrayPage/workTrayPage.spec.ts, package.json
This PR gets Cypress tests passing again - a couple of points to note:
- there is a bug in the worktray around sorting when dates are unknown - I've added a ticket for this (SV-177)
- the task view page test was failing because we had hard-coded a task ID in CRM which no longer exists. I've skipped this test because we'll just end up chasing our tail over this
(I've also added a npm task to run dev with debug enabled which makes development a lot easier
=> Fix cypress

.env.sample, package-lock.json, package.json, src/mappings/apiTaskToUiTask.test.ts, src/mappings/apiTaskToUiTask.ts, src/usecases/ui/getTasksByOfficerEmail.ts
SV-159
Adds functionality to link directly from the Worktray to the task detail view of a page.
Creates a missing link between these two views.
=> Sv 159 - Link to Task details from worktray

.prettierignore, package-lock.json, package.json
Adds a pre-commit hook to run prettier against any staged files.
Prevents the need to manually run prettier:fix before every commit to avoid a failed CI pipeline.
(No tests required as it doesn't directly affect code)
Don't forget to run npm install after merging this branch/pulling into your feature branch.
=> Install husky and pretty-quick for auto running prettier on commit

src/pages/index.tsx
I got sick of unhandled network errors on the worktray page so added some error handling so the user can seee if there is a problem rather than staring at a blank page.
=> Add some error handling to the home page

.env.sample, database.json, docker-compose.yml, serverless.yml, src/gateways/matPostgresGateway.ts, src/pages/api/tasks.ts
Refactor the way the database is configured
=> Refactor db setup

cypress.json, package.json
Single View API also runs on 3000 - I propose moving MaT service to 3100 to make running both apps together less painful
=> Move the default port for running dev to 3100 to avoid conflicts with Single View

src/pages/_app.tsx
Update CRM user id data format
To fix an issue with the user mapping
=> use the correct data format for crm id

cypress/fixtures/example.json, cypress/fixtures/tasks.json, cypress/integration/workTrayPage/workTrayPage.spec.ts, src/pages/_app.tsx, src/pages/api/tasks.ts, src/tests/pages/app.test.tsx, src/tests/pages/login-redirect.test.tsx, src/usecases/api/createUserMapping.ts, src/usecases/api/setupUser.ts
This should fix staging. There were a number of issues, which were proving difficult to troubleshoot with the code to set up users running in the getInitialProps method on every page so I moved this out of the page load and into the initial API call for getting tasks which runs on the worktray. We can move this back if we decide to but one of the benefits of this is that we don't need to query the database on every page.
The main issue was that were using client side use cases in a server context, which in theory is fine, however we were also relying on the hackneyToken cookie for authentication which obviously doesn't get set from the server.
I've refactored this out into a use case to set up the user and modified it to use the api use cases rather than the api ones.
Also, now that there …
=> Troubleshooting staging

src/pages/tasks/[id].tsx, src/usecases/api/getAuthToken.test.ts, src/usecases/api/getAuthToken.ts, src/usecases/ui/getTaskById.ts
What the title says
To fix staging
- [-] Integration tests
- [-] Cypress tests
=> Pass through the API key to APIs when called server side for the task page

.env.sample
Corrects various env vars to match new app setup (e.g. ports and local dbs)
Old env vars no longer work with the new setup, breaking new and existing local environments
=> Fix app setup

src/usecases/ui/getTaskById.ts
Use a Cookie header for auth to the API instead of an Authorization header because for some reason the auth header isn't working when deployed.
To get staging working
=> Get /tasks/[id] working in staging/prod

src/pages/_app.tsx
If a user visited the site without a cookie they would get stuck in a redirect loop - this fixes that issue
=> SV-187 - Don't redirect if on the login page even with no cookie

src/components/layout.tsx
Added link to nav bar and remove non used links.
Please check if this allows you to use singe view without logging in again.
=> SV-185/Add link to nav bar and remove non used links.

src/components/loadingPage.tsx, src/pages/index.tsx, src/pages/tasks/[id].tsx, src/usecases/ui/getTaskById.test.ts, src/usecases/ui/getTaskById.ts
A quick PR to add a reusable loading page component to use to display loading state when fetching data from the API in the client. Hooked up to the worktray and task page
=> Add loading page

cypress/fixtures/managerTask.json, cypress/integration/taskPage/taskPage.spec.ts, src/interfaces/task.ts, src/mappings/crmToTask.test.ts, src/mappings/crmToTask.ts, src/pages/tasks/[id]/index.tsx, src/tests/helpers/generateApiTaskResponse.ts, src/tests/helpers/generateCrmTaskResponse.ts, src/tests/helpers/generateTask.ts
Use the task state to determine whether the task is assigned to a manager or not
@tony-griffin You'll want to use this to determine whether to show the button to send back to the officer
=> Detect whether a task is assigned to a manager so we can show the correct buttons

.env.sample, src/components/layout.tsx
Use a public env var for the feedback link
=> Update the feedback link env var so it works in the front end

src/gateways/crmGateway.ts, src/gateways/v1MatAPIGateway.ts, src/gateways/xmlQueryStrings/getContactsByTagRef.ts, src/gateways/xmlQueryStrings/getTaskById.ts, src/interfaces/contact.ts, src/mappings/crmToContact.ts, src/mappings/v1ApiContactToContact.test.ts, src/mappings/v1ApiContactToContact.ts, src/pages/api/tasks/index.ts, src/pages/tasks/new.tsx, src/tests/helpers/mockGateways.ts, src/usecases/api/createManualTask.test.ts, src/usecases/api/createManualTask.ts, src/usecases/api/getTask.ts
Pull contacts from CRM instead of v1 api so we get the household ID to use when creating new tasks
=> Re-work the way we create new tasks to pull the contact from CRM

src/gateways/matPostgresGateway.ts, src/gateways/v1MatAPIGateway.ts, src/pages/api/healthcheck.ts, src/usecases/api/setupUser.ts
This adds more detail to the healthcheck endpoint so that it checks all env vars and connectivity to the gateways to aid in troubleshooting. Ironically, because the crm connectivity is down I couldn't add a test for the crm
Because it will help diagnosing why a service is failing.
=> Add to the healthcheck endpoint

src/usecases/api/externalProcessUrls.json, src/usecases/api/getExternalAngularProcessUrl.test.ts, src/usecases/api/getExternalAngularProcessUrl.ts
The token needs to be url encoded. Also update the list of URLs hosting the apps
=> Make sure angular tokens are url encoded

src/gateways/crmGateway.test.ts, src/gateways/crmGateway.ts, src/tests/helpers/generatePropertyPatchResponse.ts, src/usecases/api/getUser.test.ts, src/usecases/api/getUser.ts
I couldn't take it any longer :-)
=> First pass refactor to DRY up some of CRM gateway (lots more to do)

cypress/integration/workTrayPage/workTrayPage.spec.ts, src/components/layout.tsx, src/pages/_app.tsx, src/pages/index.tsx, src/pages/login-error.tsx
=> SV-197 - Add a login error page and redirect the user if they do not have a patch set

src/pages/api/tasks/index.ts, src/usecases/api/getTasksForAPatch.test.ts, src/usecases/api/getTasksForAPatch.ts
Production is swallowing errors so this exposes them - also took the opportunity to dry up the tests a little
=> Improve error output from getTasksForAPatch

src/components/dropdown.tsx
Added "labelFor" prop for drop down
To hook up label "for" and input "id" for accessibility
=> Added labelFor prop which gives value for React htmlFor in html label

src/pages/api/tasks/[id]/launch.ts
Use status code 302 in the launch process redirect
This ensures browsers will pick up the changes to process URLs set in the configuration file 
- [- ] Unit tests
- [- ] Integration tests
- [- ] Cypress tests
=> change redirect to use status code 302

serverless.yml, src/pages/api/healthcheck.ts
=> Add the PROCESS_TOKEN_ENCRYPTION_KEY env var in to serverless and healthcheck

src/pages/tasks/[id]/index.tsx
SV-201
Hides Notes and Actions on process tasks
Process tasks have their notes and actions managed in another app. Only non-process tasks should have access to these fields
=> Move notes and actions into conditional render

.eslintignore, src/components/dropdown.tsx, src/components/worktray.tsx, src/gateways/crmGateway.ts, src/gateways/v1MatAPIGateway.ts, src/gateways/xmlQueryStrings/getIntroductoryTenanciesByDate.ts, src/mappings/crmToNotes.ts, src/mappings/crmToTask.ts, src/pages/api/healthcheck.ts, src/pages/api/tasks/[id]/close.ts, src/pages/api/tasks/[id]/index.ts, src/pages/api/tasks/[id]/launch.ts, src/pages/api/tasks/[id]/notes.ts, src/pages/api/tasks/[id]/sendToManager.ts, src/pages/api/tasks/[id]/sendToOfficer.ts, src/pages/api/users.ts, src/pages/login-redirect.tsx, src/pages/tasks/[id]/index.tsx, src/pages/tasks/new.tsx, src/usecases/api/createManualTask.ts, src/usecases/api/createNote.ts, src/usecases/api/getExternalAngularProcessUrl.ts, src/usecases/api/getOfficersPerArea.ts, src/usecases/api/sendTaskToManager.ts, src/usecases/ui/createTask.ts
Fix some more lint warnings - down to 27 from 63
=> Fix more lint warnings

cypress/integration/workTrayPage/workTrayPage.spec.ts, src/pages/api/tasks/index.ts, src/pages/index.tsx, src/usecases/ui/getTasksForCurrentOfficer.test.ts, src/usecases/ui/getTasksForCurrentOfficer.ts
Update the logic to determine whether the currently logged in user is a manager or an officer and check whether they have a patch or an area assigned to them. 
Resolves the issue where managers were unable to login because they didn't have a patch
- [ x] Unit tests
- [ -] Integration tests
- [ -] Cypress tests
=> Resolve issues with managers login

serverless.yml, src/pages/api/tasks/syncItvTasks.ts, src/usecases/api/createITVTasks.ts
Now runs once a minute but only creates one task to avoid the chance of timing out
Reduces chance of bad data due to timeouts
=> Update the create ITV tasks scheduled job

src/pages/tasks/[id]/index.tsx
#What
- Change main header to H1
- Add label html element on notes text area
=> Snaglist: items 68 - 69 on list

serverless.yml
Remove next sub domain from production alias in serverless config
Some env vars were still pointing to next. sub domain which caused CORS issues in various features. This ensures everything works under the correct domain
- [-] Unit tests
- [-] Integration tests
- [-] Cypress tests
=> remove next from production alias

src/pages/api/tasks/[id]/launch.ts
Resolve an issue where 302 redirect when launching a process failed
=> remove .end from 302 redirect

src/pages/api/tasks/[id]/launch.ts
Add header first, and then end the request
To see if that fixes the redirect problem
=> add header before ending the request

cypress/integration/workTrayPage/workTrayPage.spec.ts, package-lock.json, package.json
- Update lbh-frontend-react in package json 
- Update Wortray titles in cypress test
=> update package json

src/gateways/matPostgresGateway.ts, src/tests/helpers/mockGateways.ts, src/usecases/api/closeTask.test.ts, src/usecases/api/closeTask.ts, src/usecases/api/getExternalAngularProcessUrl.test.ts, src/usecases/api/getExternalAngularProcessUrl.ts, src/usecases/api/getOfficerPatch.test.ts, src/usecases/api/getOfficerPatch.ts, src/usecases/api/getTRAs.test.ts, src/usecases/api/getTRAs.ts, src/usecases/api/sendTaskToManager.test.ts, src/usecases/api/sendTaskToManager.ts, src/usecases/api/sendTaskToOfficer.test.ts, src/usecases/api/sendTaskToOfficer.ts, src/usecases/api/setupUser.ts
Improves the way promises are used and uses the new approach for returns
consistency, consistency, consistency
=> Refactor the postgres gateway
